# Generated by Django 2.1.1 on 2018-09-20 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_auto_20180920_1620'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='picture',
            field=models.ImageField(default=None, upload_to='projects', verbose_name='Foto'),
            preserve_default=False,
        ),
    ]
